apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-deployment
  namespace: adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      imagePullSecrets:
      - name: docker
      containers:
      - name: adguard-home
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: true
          privileged: true
          runAsNonRoot: false
        image: adguard/adguardhome:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: AGH_CONFIG
          valueFrom:
            configMapKeyRef:
              name: adguard-config
              key: AdGuardHome.yaml
        ports:
        - containerPort: 53 #dns
          name: dns
          protocol: UDP
        - containerPort: 3000 #initial setup
          name: http-initial
        - containerPort: 80 #web gui
          name: http
          protocol: TCP
        volumeMounts:
        - name: adguard-conf
          mountPath: /opt/adguardhome/conf
        - name: adguard-work
          mountPath: /opt/adguardhome/work
      volumes:
      - name: adguard-work
        persistentVolumeClaim:
          claimName: adguard-work
      - name: adguard-conf
        persistentVolumeClaim:
          claimName: adguard-conf