bases:
  - repositories.yaml
  - defaults.yaml

releases:
  # User Applications
  # vaultwarden moved to ArgoCD - see /argocd/vaultwarden-application.yaml
  
  # nextcloud moved to ArgoCD - see /argocd/nextcloud-application.yaml

  # cluster-status-app moved to ArgoCD - see /argocd/cluster-status-app-application.yaml

  # couchdb moved to ArgoCD - see /argocd/couchdb-application.yaml