helmDefaults:
  verify: false
  wait: true
  timeout: 600
  recreatePods: false
  force: false
  createNamespace: true

environments:
  default:
    values:
      - domain:
          base: "vakaf.space"
        certificates:
          issuer: "cloudflare-issuer"
          acme: true
        ingress:
          className: "nginx"
          commonAnnotations:
            kubernetes.io/ingress.class: "nginx"
            kubernetes.io/tls-acme: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        resources:
          small:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          medium:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          large:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
        storage:
          storageClass: "longhorn"
          accessMode: "ReadWriteMany"
        network:
          ingressController: "nginx"
          loadBalancer: "metallb"
        monitoring:
          prometheus:
            enabled: false
          grafana:
            enabled: false
        homelab:
          timezone: "Europe/Moscow"
          cluster:
            name: "proxmox-cluster"
            environment: "homelab" 