bases:
  - repositories.yaml
  - defaults.yaml

releases:
  # Automatic DNS for Cloudflare
  - name: external-dns
    namespace: external-dns
    chart: bitnami/external-dns
    version: 9.0.0
    values:
      - ../values/network/externaldns.values.yaml.gotmpl

  # # pihole DNS filtering
  # - name: pihole-secret
  #   namespace: pihole-system
  #   chart: bedag/raw
  #   version: 2.0.0
  #   values:
  #     - ../../manifests/pihole/secret.yaml
  #   installed: false

  # - name: pihole-externaldns-rbac
  #   namespace: pihole-system
  #   chart: bedag/raw
  #   version: 2.0.0
  #   values:
  #     - ../../manifests/pihole/externaldns-rbac.yaml
  #   installed: false

  # - name: pihole-externaldns
  #   namespace: pihole-system
  #   chart: bedag/raw
  #   version: 2.0.0
  #   values:
  #     - ../../manifests/pihole/externaldns.yaml
  #   needs:
  #     - pihole-secret
  #     - pihole-externaldns-rbac
  #   installed: false

  # - name: pihole
  #   namespace: pihole-system
  #   chart: mojo2600/pihole
  #   version: 2.31.0
  #   values:
  #     - ../values/network/pihole.values.yaml.gotmpl
  #   needs:
  #     - pihole-secret
  #   installed: false

  # # HAProxy Load Balancer for PostgreSQL Database
  # - name: haproxy-postgres
  #   namespace: database-system
  #   chart: haproxytech/haproxy
  #   version: 1.24.0
  #   values:
  #     - ../values/network/haproxy-postgres.values.yaml
  #   installed: false

  # # External Service for HAProxy PostgreSQL
  # - name: haproxy-postgres-service
  #   namespace: database-system
  #   chart: bedag/raw
  #   version: 2.0.0
  #   values:
  #     - ../../manifests/proxy/haproxy-postgres-service.yaml
  #   needs:
  #     - haproxy-postgres 
  #   installed: false