resources:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: keycloak
      namespace: keycloak
      annotations:
        cert-manager.io/cluster-issuer: cloudflare-issuer
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
        nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
        # External-DNS аннотации
        external-dns.alpha.kubernetes.io/hostname: "keycloak.vakaf.space"
        external-dns.alpha.kubernetes.io/target: "91.77.167.6"
        external-dns.alpha.kubernetes.io/ttl: "300"
    spec:
      ingressClassName: nginx
      tls:
      - hosts:
        - keycloak.vakaf.space
        secretName: keycloak-tls-secret
      rules:
      - host: keycloak.vakaf.space
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080