resources:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: keycloak-secret
      namespace: keycloak
    type: Opaque
    data:
      # echo -n 'change_me' | base64
      admin-password: Y2hhbmdlX21l 