apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
  namespace: adguard
data:

  AdGuardHome.yaml: |
    http:
      address: 0.0.0.0:80
      session_ttl: 720h
    users:
      - name: ivan
        password: $2a$10$Wl814vGJDceXYxgYD0Pi1.bScJN82QcgrK/TmP/SVCOLl5yrSCRT6
    auth_attempts: 5
    block_auth_min: 15
    http_proxy: ""
    language: ""
    theme: auto
    debug_pprof: false
    dns:
      bind_hosts:
        - 0.0.0.0
      port: 53
      anonymize_client_ip: false
      protection_enabled: true
      blocking_mode: default
      blocking_ipv4: ""
      blocking_ipv6: ""
      blocked_response_ttl: 10
      protection_disabled_until: null
      parental_block_host: family-block.dns.adguard.com
      safebrowsing_block_host: standard-block.dns.adguard.com
      ratelimit: 20
      ratelimit_whitelist: []
      refuse_any: true
      upstream_dns:
        - https://dns10.quad9.net/dns-query
        - https://1.1.1.1/dns-query
        - https://1.0.0.1/dns-query
      upstream_dns_file: ""
      bootstrap_dns:
        - 9.9.9.10
        - 149.112.112.10
        - 2620:fe::10
        - 2620:fe::fe:10
      all_servers: true
      fastest_addr: false
      fastest_timeout: 1s
      allowed_clients: []
      disallowed_clients: []
      blocked_hosts:
        - version.bind
        - id.server
        - hostname.bind
      trusted_proxies:
        - 127.0.0.0/8
        - ::1/128
      cache_size: 4194304
      cache_ttl_min: 0
      cache_ttl_max: 0
      cache_optimistic: false
      bogus_nxdomain: []
      aaaa_disabled: false
      enable_dnssec: false
      edns_client_subnet:
        custom_ip: ""
        enabled: false
        use_custom: false
      max_goroutines: 300
      handle_ddr: true
      ipset: []
      ipset_file: ""
      bootstrap_prefer_ipv6: false
      filtering_enabled: true
      filters_update_interval: 24
      parental_enabled: false
      safebrowsing_enabled: false
      safebrowsing_cache_size: 1048576
      safesearch_cache_size: 1048576
      parental_cache_size: 1048576
      cache_time: 30
      safe_search:
        enabled: false
        bing: true
        duckduckgo: true
        google: true
        pixabay: true
        yandex: true
        youtube: true
      rewrites:
        - domain: '*.okd.local'
          answer: 10.11.12.210
        - domain: '*.vakaf.space'
          answer: 10.11.12.18
        - domain: '*.home.space'
          answer: 10.11.12.210
      blocked_services:
        schedule:
          time_zone: UTC
        ids: []
      upstream_timeout: 10s
      private_networks: []
      use_private_ptr_resolvers: true
      local_ptr_upstreams: []
      use_dns64: false
      dns64_prefixes: []
      serve_http3: false
      use_http3_upstreams: false
    tls:
      enabled: true
      server_name: adguard.vakaf.keenetic.link
      force_https: true
      port_https: 443
      port_dns_over_tls: 853
      port_dns_over_quic: 853
      port_dnscrypt: 0
      dnscrypt_config_file: ""
      allow_unencrypted_doh: false
      certificate_chain: |-
        -----BEGIN CERTIFICATE-----
        MIIENzCCAx+gAwIBAgISA8fjQ75coag0C3Zlvp/3kmU9MA0GCSqGSIb3DQEBCwUA
        MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
        EwJSMzAeFw0yMzA3MTYxMDU4MTZaFw0yMzEwMTQxMDU4MTVaMCYxJDAiBgNVBAMT
        G2FkZ3VhcmQudmFrYWYua2VlbmV0aWMubGluazBZMBMGByqGSM49AgEGCCqGSM49
        AwEHA0IABG9pl26IrJCGisrbcB8Kg9upRzVC3DVIFiNKPOKarJF5ES2SrqB+IgQP
        fq8eXf3SPnQr8TY21m6dyIOPOWk4MDijggIcMIICGDAOBgNVHQ8BAf8EBAMCB4Aw
        HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYD
        VR0OBBYEFHeFDFHS0l9QV9tsHMCczuRZhdNVMB8GA1UdIwQYMBaAFBQusxe3WFbL
        rlAJQOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0cDov
        L3IzLm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5jci5v
        cmcvMCYGA1UdEQQfMB2CG2FkZ3VhcmQudmFrYWYua2VlbmV0aWMubGluazATBgNV
        HSAEDDAKMAgGBmeBDAECATCCAQMGCisGAQQB1nkCBAIEgfQEgfEA7wB1ALc++yTf
        nE26dfI5xbpY9Gxd/ELPep81xJ4dCYEl7bSZAAABiV6Q0GgAAAQDAEYwRAIgLbkl
        r0/MQNYG9yOjY6Xk/X3LKQbuE5m5XAJiC98MfwsCIBhqmSdD2l9Iu+U91XvQOmIp
        bwjrQftYzqCPZK9pRom0AHYA6D7Q2j71BjUy51covIlryQPTy9ERa+zraeF3fW0G
        vW4AAAGJXpDQaQAABAMARzBFAiA3viU67HJ3HWnzWtdW3GgiB6w8VJ7dPHtep8yb
        YWIYMgIhAKg/0wZsF5dg6Ass97HGEavw0gBytN898P85YGAYeriLMA0GCSqGSIb3
        DQEBCwUAA4IBAQAHMOxT/vlTsxW6dYyBAxk9zTOSRjQOVLjwymB7hYqIKws05DtZ
        0IVU6R5DxeR7oDItakQUJUNmvKi47VCYF2yG/zn7QTgs7aX08/+01vsnC1HWZynC
        QN/M+IRK37OuSuz1uJj/qYMgX43C22xwG7Xsy4j0nAlmzt8EDzs2f27lvIJ0aLPI
        kxVJtMxZ8VSUJ/AY/mWMR9BFyMBEQv8Ouj0XyFQcVaJPenE2g39rL0uT2/AayWFQ
        /JzUXks1nOxqUqq/0DPuovzV5itA5lt239GQZocv/C2RZMTJBVyelD3IobUblGkM
        aoVz9SsBoUKlOXyc6wFv8iWVZxXv4FKTrbSP
        -----END CERTIFICATE-----
      private_key: |-
        -----BEGIN PRIVATE KEY-----
        MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg/0y8kiPc9Q9oMeea
        6PQDN6hKoiBPgjGLNHYFp64zB9mhRANCAARvaZduiKyQhorK23AfCoPbqUc1Qtw1
        SBYjSjzimqyReREtkq6gfiIED36vHl390j50K/E2NtZunciDjzlpODA4
        -----END PRIVATE KEY-----
      certificate_path: ""
      private_key_path: ""
      strict_sni_check: false
    querylog:
      ignored: []
      interval: 2160h
      size_memory: 1000
      enabled: true
      file_enabled: true
    statistics:
      ignored: []
      interval: 24h
      enabled: true
    filters:
      - enabled: true
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
        name: AdGuard DNS filter
        id: 1
      - enabled: true
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
        name: AdAway Default Blocklist
        id: 2
      - enabled: true
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_24.txt
        name: 1Hosts (Lite)
        id: 1689495819
      - enabled: true
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_4.txt
        name: Dan Pollock's List
        id: 1689495820
      - enabled: true
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_34.txt
        name: HaGeZi Personal Black & White
        id: 1689495821
      - enabled: true
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_38.txt
        name: 1Hosts (mini)
        id: 1689495822
      - enabled: true
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_32.txt
        name: The NoTracking blocklist
        id: 1689495823
      - enabled: true
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_5.txt
        name: OISD Blocklist Small
        id: 1689495824
      - enabled: true
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt
        name: OISD Blocklist Big
        id: 1689495825
      - enabled: true
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_3.txt
        name: Peter Lowe's Blocklist
        id: 1689495826
      - enabled: true
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_33.txt
        name: Steven Black's List
        id: 1689495827
      - enabled: true
        url: https://raw.githubusercontent.com/alexsannikov/adguardhome-filters/master/admalware.txt
        name: https://github.com/alexsannikov/adguardhome-filters
        id: 1689495829
      - enabled: true
        url: https://raw.githubusercontent.com/alexsannikov/adguardhome-filters/master/fakenews.txt
        name: https://raw.githubusercontent.com/alexsannikov/adguardhome-filters/master/fakenews.txt
        id: 1689495830
      - enabled: true
        url: https://raw.githubusercontent.com/alexsannikov/adguardhome-filters/master/gambling.txt
        name: https://raw.githubusercontent.com/alexsannikov/adguardhome-filters/master/gambling.txt
        id: 1689495831
      - enabled: true
        url: https://raw.githubusercontent.com/alexsannikov/adguardhome-filters/master/rueasylist.txt
        name: https://raw.githubusercontent.com/alexsannikov/adguardhome-filters/master/rueasylist.txt
        id: 1689495832
      - enabled: true
        url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
        name: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
        id: 1689495838
      - enabled: true
        url: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
        name: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
        id: 1689495839
      - enabled: true
        url: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
        name: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
        id: 1689495840
      - enabled: true
        url: https://v.firebog.net/hosts/static/w3kbl.txt
        name: https://v.firebog.net/hosts/static/w3kbl.txt
        id: 1689495841
      - enabled: true
        url: https://adaway.org/hosts.txt
        name: https://adaway.org/hosts.txt
        id: 1689495842
      - enabled: true
        url: https://v.firebog.net/hosts/AdguardDNS.txt
        name: https://v.firebog.net/hosts/AdguardDNS.txt
        id: 1689495843
      - enabled: true
        url: https://v.firebog.net/hosts/Admiral.txt
        name: https://v.firebog.net/hosts/Admiral.txt
        id: 1689495844
      - enabled: true
        url: https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
        name: https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
        id: 1689495845
      - enabled: true
        url: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
        name: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
        id: 1689495846
      - enabled: true
        url: https://v.firebog.net/hosts/Easylist.txt
        name: https://v.firebog.net/hosts/Easylist.txt
        id: 1689495847
      - enabled: true
        url: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
        name: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
        id: 1689495848
      - enabled: true
        url: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
        name: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
        id: 1689495849
      - enabled: true
        url: https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
        name: https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
        id: 1689495850
      - enabled: true
        url: https://v.firebog.net/hosts/Easyprivacy.txt
        name: https://v.firebog.net/hosts/Easyprivacy.txt
        id: 1689495851
      - enabled: true
        url: https://v.firebog.net/hosts/Prigent-Ads.txt
        name: https://v.firebog.net/hosts/Prigent-Ads.txt
        id: 1689495852
      - enabled: true
        url: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
        name: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
        id: 1689495853
      - enabled: true
        url: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
        name: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
        id: 1689495854
      - enabled: true
        url: https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
        name: https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
        id: 1689495855
      - enabled: true
        url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
        name: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
        id: 1689495856
      - enabled: true
        url: https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
        name: https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
        id: 1689495857
      - enabled: true
        url: https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
        name: https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
        id: 1689495858
      - enabled: true
        url: https://v.firebog.net/hosts/Prigent-Crypto.txt
        name: https://v.firebog.net/hosts/Prigent-Crypto.txt
        id: 1689495859
      - enabled: true
        url: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
        name: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
        id: 1689495860
      - enabled: true
        url: https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
        name: https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
        id: 1689495861
      - enabled: true
        url: https://phishing.army/download/phishing_army_blocklist_extended.txt
        name: https://phishing.army/download/phishing_army_blocklist_extended.txt
        id: 1689495862
      - enabled: true
        url: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
        name: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
        id: 1689495863
      - enabled: true
        url: https://v.firebog.net/hosts/RPiList-Malware.txt
        name: https://v.firebog.net/hosts/RPiList-Malware.txt
        id: 1689495864
      - enabled: true
        url: https://v.firebog.net/hosts/RPiList-Phishing.txt
        name: https://v.firebog.net/hosts/RPiList-Phishing.txt
        id: 1689495865
      - enabled: true
        url: https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
        name: https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
        id: 1689495866
      - enabled: true
        url: https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
        name: https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
        id: 1689495867
      - enabled: true
        url: https://urlhaus.abuse.ch/downloads/hostfile/
        name: https://urlhaus.abuse.ch/downloads/hostfile/
        id: 1689495868
      - enabled: true
        url: https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
        name: https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
        id: 1689495869
      - enabled: true
        url: https://schakal.ru/hosts/hosts_mail_fb.txt
        name: https://schakal.ru/hosts/hosts_mail_fb.txt
        id: 1689495871
    whitelist_filters: []
    user_rules:
      - '@@||instagram.com^$important'
      - '@@||facebook.com^$important'
      - '@@||static.cdninstagram.com^$important'
      - '@@||scontent-ams2-1.cdninstagram.com^$important'
      - '@@||scontent-ams4-1.cdninstagram.com^$important'
      - '@@||scontent-hel3-1.cdninstagram.com^$important'
      - '@@||yastatic.net^$important'
      - '@@||avatars.mds.yandex.net^$important'
      - '@@||csp.yandex.net^$important'
      - '@@||cloud-api.yandex.ru^$important'
      - '@@||tiles.api-maps.yandex.ru^$important'
      - '@@||core-renderer-tiles.maps.yandex.net^$important'
      - '@@||ru.superchat.live^$important'
      - '@@||api.vk.com^$important'
      - '@@||vk.com^$important'
      - '@@||api.messenger.yandex.net^$important'
      - '@@||mobileproxy.passport.yandex.net^$important'
      - '@@||tools.messenger.yandex.net^$important'
      - '@@||mapi.vs.market.yandex.net^$important'
      - '@@||api.plus.yandex.ru^$important'
      - ""
    dhcp:
      enabled: false
      interface_name: ""
      local_domain_name: lan
      dhcpv4:
        gateway_ip: ""
        subnet_mask: ""
        range_start: ""
        range_end: ""
        lease_duration: 86400
        icmp_timeout_msec: 1000
        options: []
      dhcpv6:
        range_start: ""
        lease_duration: 86400
        ra_slaac_only: false
        ra_allow_slaac: false
    clients:
      runtime_sources:
        whois: true
        arp: true
        rdns: true
        dhcp: true
        hosts: true
      persistent: []
    log:
      file: ""
      max_backups: 0
      max_size: 100
      max_age: 3
      compress: false
      local_time: false
      verbose: false
    os:
      group: ""
      user: ""
      rlimit_nofile: 0
    schema_version: 24
