apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitleaks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: gitleaks
  sources:
    # Helm chart from securecodebox repository
    - repoURL: https://charts.securecodebox.io
      chart: gitleaks
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/infrastructure/gitleaks.yaml
    # Values repository
    - repoURL: git@github.com:VizzleTF/home-proxmox-values.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m