"all":
  "children":
    "etcd":
      "hosts":
        "kube-node-01": {}
        "kube-node-02": {}
        "kube-node-03": {}
    "k8s_cluster":
      "children":
        "kube_control_plane": {}
        "kube_node": {}
    "kube_control_plane":
      "hosts":
        "kube-node-01": {}
        "kube-node-02": {}
    "kube_node":
      "hosts":
        "kube-node-01": {}
        "kube-node-02": {}
        "kube-node-03": {}
        "kube-node-04": {}
        "kube-node-05": {}
    "oracle_linux":
      "hosts":
        "kube-node-01": {}
        "kube-node-02": {}
        "kube-node-03": {}
        "kube-node-04": {}
        "kube-node-05": {}
  "hosts":
    "kube-node-01":
      "access_ip": "10.11.12.241"
      "ansible_host": "10.11.12.241"
      "ansible_user": "root"
      "ip": "10.11.12.241"
    "kube-node-02":
      "access_ip": "10.11.12.242"
      "ansible_host": "10.11.12.242"
      "ansible_user": "root"
      "ip": "10.11.12.242"
    "kube-node-03":
      "access_ip": "10.11.12.243"
      "ansible_host": "10.11.12.243"
      "ansible_user": "root"
      "ip": "10.11.12.243"
    "kube-node-04":
      "access_ip": "10.11.12.145"
      "ansible_host": "10.11.12.145"
      "ansible_user": "root"
      "ip": "10.11.12.145"
    "kube-node-05":
      "access_ip": "10.11.12.146"
      "ansible_host": "10.11.12.146"
      "ansible_user": "root"
      "ip": "10.11.12.146"