"all":
  "children":
    "common-db":
      "hosts":
        "patroni-etcd-01": {}
        "patroni-postgres-01": {}
        "patroni-postgres-02": {}
    "common-etcd":
      "hosts":
        "patroni-etcd-01": {}
    "common-patroni":
      "hosts":
        "patroni-postgres-01": {}
        "patroni-postgres-02": {}
    "etcd":
      "hosts":
        "kube-node-01": {}
        "kube-node-02": {}
        "kube-node-03": {}
    "k8s_cluster":
      "children":
        "kube_control_plane": {}
        "kube_node": {}
    "kube_control_plane":
      "hosts":
        "kube-node-01": {}
        "kube-node-02": {}
    "kube_node":
      "hosts":
        "kube-node-01": {}
        "kube-node-02": {}
        "kube-node-03": {}
        "kube-node-04": {}
    "oracle_linux":
      "hosts":
        "kube-node-01": {}
        "kube-node-02": {}
        "kube-node-03": {}
        "kube-node-04": {}
        "patroni-etcd-01": {}
        "patroni-postgres-01": {}
        "patroni-postgres-02": {}
  "hosts":
    "kube-node-01":
      "access_ip": "10.11.12.241"
      "ansible_host": "10.11.12.241"
      "ansible_user": "root"
      "ip": "10.11.12.241"
    "kube-node-02":
      "access_ip": "10.11.12.242"
      "ansible_host": "10.11.12.242"
      "ansible_user": "root"
      "ip": "10.11.12.242"
    "kube-node-03":
      "access_ip": "10.11.12.243"
      "ansible_host": "10.11.12.243"
      "ansible_user": "root"
      "ip": "10.11.12.243"
    "kube-node-04":
      "access_ip": "10.11.12.145"
      "ansible_host": "10.11.12.145"
      "ansible_user": "root"
      "ip": "10.11.12.145"
    "patroni-etcd-01":
      "access_ip": "10.11.12.246"
      "ansible_host": "10.11.12.246"
      "ansible_user": "root"
      "ip": "10.11.12.246"
    "patroni-postgres-01":
      "access_ip": "10.11.12.247"
      "ansible_host": "10.11.12.247"
      "ansible_user": "root"
      "ip": "10.11.12.247"
    "patroni-postgres-02":
      "access_ip": "10.11.12.245"
      "ansible_host": "10.11.12.245"
      "ansible_user": "root"
      "ip": "10.11.12.245"
      