- name: Installing list of packages
  package: name="{{ packages }}" state=present

- name: Generate iSCSI initiator name
  ansible.builtin.command: /sbin/iscsi-iname
  register: iscsi_initiator_name
  changed_when: false

- name: Set initiator name in config file
  ansible.builtin.copy:
    content: "InitiatorName={{ iscsi_initiator_name.stdout }}"
    dest: /etc/iscsi/initiatorname.iscsi
    mode: '0644'

- name: Enable iscsid service
  ansible.builtin.systemd:
    name: iscsid
    enabled: yes

- name: Start iscsid service
  ansible.builtin.systemd:
    name: iscsid
    state: started