ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "kuma.vakaf.space"
    external-dns.alpha.kubernetes.io/target: "91.77.167.6"
    cert-manager.io/cluster-issuer: cloudflare-issuer
  hosts:
    - host: kuma.vakaf.space
      paths:
        - path: /
          pathType: Prefix 
  tls:
    - secretName: uptime-kuma-tls
      hosts:
        - kuma.vakaf.space

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi