image:
  repository: coturn/coturn
  tag: "4.6.3"

replicaCount: 1

service:
  type: LoadBalancer
  port: 3478
  portName: stun-turn
  annotations:
    # External-DNS аннотации
    external-dns.alpha.kubernetes.io/hostname: "netbird-coturn.vakaf.space"
    external-dns.alpha.kubernetes.io/target: "10.11.12.162"
    external-dns.alpha.kubernetes.io/ttl: "300"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

config:
  realm: "netbird.vakaf.space"
  verbose: false
  fingerprint: true
  lt_cred_mech: true
  use_auth_secret: true
  static_auth_secret_env: COTURN_STATIC_SECRET
  log_file: stdout
  no_dtls: true
  no_tls: true

env:
  - name: COTURN_STATIC_SECRET
    valueFrom:
      secretKeyRef:
        name: coturn-secret
        key: password

persistence:
  enabled: false

ingress:
  enabled: false 