# Crossplane values configuration

# Enable metrics for monitoring
metrics:
  enabled: true

# Resource requests and limits for better resource management
resourcesCrossplane:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi

resourcesRBACManager:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# Enable webhooks for validation
webhooks:
  enabled: true

# Leader election for HA
leaderElection: true

# RBAC Manager configuration
rbacManager:
  deploy: true
  leaderElection: true
  replicas: 1 