controller:
  allowSnippetAnnotations: "true"
  service:
    type: LoadBalancer
    loadBalancerIP: 10.11.12.160
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"