nextcloud:
  host: nc.vakaf.space
  username: ivan
  password: "changeme"

  # objectStore:
  #   s3:
  #     enabled: true
  #     host: "http://seaweedfs-s3.seaweedfs.svc.cluster.local"
  #     bucket: "nextcloud"  
  #     port: "8333"  
  #     ssl: false  
  #     region: "us-east-1"  
  #     accessKey: "i7vF6DLIGZA3Hb4q"
  #     secretKey: "go95Sg2aHzbHHvBFtUmn68OFzm6lCVem"
  #     autoCreate: true 
  #     # legacyAuth: true
  #     usePathStyle: true
  extraVolumes:
   - name: nfs-backup
     nfs:
       server: "10.11.12.213"
       path: "/nfs-share/nc/backups"
       readOnly: false
  extraVolumeMounts:
   - name: nfs-backup
     mountPath: "/backup"

replicaCount: 1

resources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 2
    memory: 2Gi

service:
  type: LoadBalancer
  loadBalancerIP: "10.11.12.165"

persistence:
  enabled: true
  accessMode: ReadWriteMany
  size: 40Gi

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 4G
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: cloudflare-issuer
    nginx.ingress.kubernetes.io/server-snippet: |-
      server_tokens off;
      proxy_hide_header X-Powered-By;
      rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
      rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
      rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
      rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
      location = /.well-known/carddav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /.well-known/caldav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
      }
      location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
      }
      location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
        deny all;
      }
  tls:
    - hosts:
      - nc.vakaf.space
      secretName: nextcloud-tls

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: nextcloud
        password: sup3rstr0ngP@s$
        database: nextcloud
  primary:
    persistence:
      enabled: true
      accessMode: ReadWriteMany
      size: 1Gi
    resources:
      limits:
        cpu: 1
        ephemeral-storage: 1Gi
        memory: 1Gi
      requests:
        cpu: 500m
        ephemeral-storage: 50Mi
        memory: 512Mi

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: your-redis-password
  master:
    persistence:
      enabled: true  
      accessMode: ReadWriteMany
      size: 1Gi

internalDatabase:
  enabled: false

cronjob:
  enabled: true

externalDatabase:
  enabled: true
  type: postgresql
  host: '{{ .Release.Name }}-postgresql'
  user: nextcloud
  password: sup3rstr0ngP@s$
  database: nextcloud

# FOR THE FIRST TIME. BUG WITH RWX VOLUME
# startupProbe:
#   enabled: true
#   initialDelaySeconds: 7200
#   periodSeconds: 60
#   timeoutSeconds: 5
#   failureThreshold: 15
#   successThreshold: 1