---
admin:
  enabled: true
  existingSecret: "pihole-secret"
  passwordKey: "password"

replicaCount: 1

persistentVolumeClaim:
  enabled: true
  size: 1Gi

ingress:
  ingressClassName: nginx
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
  hosts:
    - "pihole.vakaf.space"
  tls:
    - secretName: pihole-tls
      hosts:
        - "pihole.vakaf.space"

serviceWeb:
  loadBalancerIP: 10.11.12.171
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 10.11.12.170
  type: LoadBalancer
  mixedService: true

DNS1: 10.11.12.52
DNS2: 10.11.12.1

# Настройки FTL через переменные окружения  
extraEnvVars:
  FTLCONF_dns_listeningMode: "ALL"

adlists:
  - https://schakal.ru/hosts/alive_hosts_ru_com.txt
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  - https://blocklistproject.github.io/Lists/abuse.txt
  - https://blocklistproject.github.io/Lists/ads.txt
  - https://blocklistproject.github.io/Lists/malware.txt
  - https://blocklistproject.github.io/Lists/phishing.txt
  - https://blocklistproject.github.io/Lists/scam.txt
  - https://blocklistproject.github.io/Lists/tracking.txt
  - https://big.oisd.nl
  - https://adaway.org/hosts.txt
  - https://v.firebog.net/hosts/AdguardDNS.txt
  - https://v.firebog.net/hosts/Admiral.txt
  - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
  - https://v.firebog.net/hosts/Easylist.txt
  - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
  - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
  - https://v.firebog.net/hosts/Easyprivacy.txt
  - https://v.firebog.net/hosts/Prigent-Ads.txt
  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
  - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
  - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
  - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
  - https://v.firebog.net/hosts/Prigent-Crypto.txt
  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
  - https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
  - https://phishing.army/download/phishing_army_blocklist_extended.txt
  - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
  - https://v.firebog.net/hosts/RPiList-Malware.txt
  - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
  - https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
  - https://urlhaus.abuse.ch/downloads/hostfile/
  - https://lists.cyberhost.uk/malware.txt
  - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
  - https://v.firebog.net/hosts/static/w3kbl.txt