storage:
  data: 
    name: "vaultwarden-data"
    size: "2Gi"
    class: "longhorn"
    accessMode: "ReadWriteMany"
    # keepPvc: false

domain: "https://pass.vakaf.space"

ingress:
  enabled: true
  hostname: "pass.vakaf.space"
  class: "nginx"
  tlsSecret: vw-tls
  additionalAnnotations: 
    cert-manager.io/cluster-issuer: cloudflare-issuer