data: 
  name: "vaultwarden-data"
  size: "2Gi"
  path: "/data"
  # keepPvc: false

domain: "https://pass.vakaf.space"

ingress:
  enabled: true
  hostname: "pass.vakaf.space"
  class: "nginx"
  tlsSecret: vw-tls
  additionalAnnotations: 
    cert-manager.io/cluster-issuer: letsencrypt