apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-backup-lxc
  namespace: nextcloud
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sync
            image: instrumentisto/rsync-ssh
            command: ["rsync", "-avz", "--no-owner", "--no-group", "--no-times", "--delete", "/source/config/config.php", "/source/data/ivan/files", "/destination/"]
            volumeMounts:
            - name: longhorn-volume
              mountPath: /source
            - name: nfs-volume
              mountPath: /destination
          restartPolicy: OnFailure
          volumes:
          - name: longhorn-volume
            persistentVolumeClaim:
              claimName: nextcloud-nextcloud
          - name: nfs-volume
            nfs:
              server: 10.11.12.120
              path: "/nfs-share/nc"