apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-nc-db
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs-share/nc_db
    server: 10.11.12.213