apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-nc
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /nfs-share/nc
    server: 10.11.12.213