apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-prom
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /nfs-share/prom
    server: 10.11.12.213