apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-grafana
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /nfs-share/grafana
    server: 10.11.12.213