- name: Install NFS utils
  package:
    name: nfs-utils
    state: present

- name: Create NFS directory
  file:
    path: /nfs-share
    state: directory
    mode: 1777
    owner: nobody
    group: nobody

- name: Add clients to exports
  lineinfile:
    path: /etc/exports
    line: "{{ item }}"
    create: yes
  loop:
    - "/nfs-share  10.11.12.201(rw)"
    - "/nfs-share  10.11.12.202(rw)"
    - "/nfs-share  10.11.12.203(rw)"

- name: Restart NFS services
  systemd:
    name: nfs-server
    state: restarted
    enabled: true
    masked: no
