resources:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: external-dns
    spec:
      strategy:
        type: Recreate
      selector:
        matchLabels:
          app: external-dns
      template:
        metadata:
          labels:
            app: external-dns
        spec:
          serviceAccountName: external-dns
          containers:
          - name: external-dns
            image: registry.k8s.io/external-dns/external-dns:v0.17.0
            # If authentication is disabled and/or you didn't create
            # a secret, you can remove this block.
            env:
              - name: EXTERNAL_DNS_PIHOLE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: pihole-secret
                    key: password
            args:
              - --source=service
              - --source=ingress
              # Pihole only supports A/CNAME records so there is no mechanism to track ownership.
              # You don't need to set this flag, but if you leave it unset, you will receive warning
              # logs when ExternalDNS attempts to create TXT records.
              - --registry=noop
              # IMPORTANT: If you have records that you manage manually in Pi-hole, set
              # the policy to upsert-only so they do not get deleted.
              - --policy=sync
              - --provider=pihole
              # Change this to the actual address of your Pi-hole web server
              - --pihole-server=http://pihole-web.pihole-system.svc.cluster.local
              # Use API version 6 for Pi-hole v6
              - --pihole-api-version=6
            resources:
              limits:
                cpu: 1
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 256M
          securityContext:
            fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes token files