apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: proxmox-credentials
  namespace: cluster-status
data:
  api-url: aHR0cHM6Ly8xMC4xMS4xMi41MTo4MDA2L2FwaTIvanNvbg==
  username: cm9vdEBwYW0=
  password: <password-in-base64>