---
- name: Configure Oracle VM
  hosts: all
  roles:
    - oracle_firewalld_disable
    - oracle_selinux_disable
    - oracle_timezone_set
    - oracle_increase_lvm_size
    - oracle_install_packages

- name: Configure Oracle VM
  hosts: kube_node
  roles:
    - oracle_kn_install_packages