resources:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: crowdsec-secret
      namespace: crowdsec
      annotations:
        # Разрешить reflector копировать этот секрет
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        # Разрешить копирование только в specific namespaces
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "ingress-nginx"
        # Автоматически создать зеркала секрета в других namespace'ах
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        # Автоматически создать зеркало в ingress-nginx namespace
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "ingress-nginx"
    type: Opaque
    data:
      # for crowdsec console
      enroll-key: ""
      # for crowdsec bouncer
      bouncer-api-key: ""