apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant-proxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:VizzleTF/home-proxmox-values.git
    targetRevision: HEAD
    path: manifests/homeassistant
  destination:
    server: https://kubernetes.default.svc
    namespace: homeassistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
