apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    # Разрешить reflector копировать этот секрет
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    # Разрешить копирование только в specific namespaces
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "external-dns"
    # Автоматически создать зеркала секрета в других namespace'ах
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    # Автоматически создать зеркало в external-dns namespace
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "external-dns"
type: Opaque
stringData:
  api-token: 'change_me'  # Замените на ваш реальный Cloudflare API токен