tags:
  - terraform
vms:
  - vm_id: 301
    vm_name: kube-node-01
    address: 10.11.12.241/24
    node_name: pve3
    cores: 4
    ram: 12288
    disk_size: 100
    usb:
      host: "1a86:55d4" # zigbee stick
      mapping:
      usb3: false
    tags: [kube_control_plane, kube_node, etcd, oracle_linux]
    pool_id: k8s-pool
    description: "<div align='center'><img src='https://www.allangray.co.za/globalassets/information-technology/kubernetes.png' /></div>"
  - vm_id: 302
    vm_name: kube-node-02
    address: 10.11.12.242/24
    node_name: pve4
    cores: 4
    ram: 12288
    disk_size: 100
    tags: [kube_control_plane, kube_node, etcd, oracle_linux]
    pool_id: k8s-pool
    description: "<div align='center'><img src='https://www.allangray.co.za/globalassets/information-technology/kubernetes.png' /></div>"
  - vm_id: 303
    vm_name: kube-node-03
    address: 10.11.12.243/24
    node_name: pve5
    cores: 4
    ram: 12288
    disk_size: 100
    tags: [kube_node, etcd, oracle_linux]
    pool_id: k8s-pool
    description: "<div align='center'><img src='https://www.allangray.co.za/globalassets/information-technology/kubernetes.png' /></div>"