resources:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: keycloak-credentials
      namespace: crossplane-system
      labels: 
        type: provider-credentials
    type: Opaque
    stringData:
      credentials: |
        {
          "client_id": "admin-cli",
          "username": "admin",
          "password": "change_me",
          "url": "https://YOUR_KEYCLOAK_URL",
          "base_path": "",
          "realm": "master"
        }

  - apiVersion: keycloak.crossplane.io/v1beta1
    kind: ProviderConfig
    metadata:
      name: default
      namespace: crossplane-system
    spec:
      credentials:
        source: Secret
        secretRef:
          name: keycloak-credentials
          key: credentials
          namespace: crossplane-system 