# brew install helm
# helm plugin install https://github.com/databus23/helm-diff
# brew install helmfile
# helmfile apply

repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb
  # - name: mojo2600
  #   url: https://mojo2600.github.io/pihole-kubernetes
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack            	
    url: https://charts.jetstack.io                        
  - name: nextcloud           	
    url: https://nextcloud.github.io/helm/                 
  - name: vaultwarden         	
    url: https://guerzon.github.io/vaultwarden
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server
  - name: cluster-status-app
    url: https://vizzletf.github.io/cluster-status-app
  # - name: k8s-at-home
  #   url: https://k8s-at-home.com/charts/
  # - name: seaweedfs
  #   url: https://seaweedfs.github.io/seaweedfs/helm
  # - name: seaweedfs-csi-driver
  #   url: https://seaweedfs.github.io/seaweedfs-csi-driver/helm
  # - name: prometheus-community	
  #   url: https://prometheus-community.github.io/helm-charts
  # - name: grafana             	
  #   url: https://grafana.github.io/helm-charts             
  # - name: vm                  	
  #   url: https://victoriametrics.github.io/helm-charts
  # - name: ollama
  #   url: https://otwld.github.io/ollama-helm
  # - name: open-webui
  #   url: https://helm.openwebui.com/
  # - name: pajikos 
  #   url: http://pajikos.github.io/home-assistant-helm-chart   

---
releases:
  # Distributed storage
  # ssh root@all_nodes yum install iscsi-initiator-utils lsscsi -y
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.8.0
    values:
      - ./values/longhorn.values.yaml

  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.14.9

  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    namespace: ingress-nginx
    version: 4.12.0
    values:
      - ./values/ingress-nginx.values.yaml
  
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.16.3
    values:
      - ./values/cert-manager.values.yaml

  - name: vaultwarden
    namespace: vaultwarden
    chart: vaultwarden/vaultwarden
    version: 0.31.3
    values:
      - ./values/vaultwarden.values.yaml

  - name: nextcloud
    namespace: nextcloud
    chart: nextcloud/nextcloud
    version: 6.6.3
    values:
      - ./values/nextcloud.values.yaml

  - name: metrics-server
    namespace: kube-system
    chart: metrics-server/metrics-server
    version: 3.12.2
    values:
      - ./values/metrics-server.values.yaml

  - name: cluster-status-app
    namespace: cluster-status
    chart: cluster-status-app/cluster-status-app
    version: 0.4.4
    values:
      - ./values/cluster-status-app.values.yaml

  # - name: torrserver
  #   namespace: torrserver
  #   chart: k8s-at-home/torrserver
  #   version: 1.2.2
  #   values:
  #     - ./values/torrserver.values.yaml

  # - name: seaweedfs
  #   namespace: seaweedfs
  #   chart: seaweedfs/seaweedfs
  #   version: 4.0.0
  #   values:
  #     - ./values/seaweedfs.values.yaml
  
  # - name: seaweedfs-csi-driver
  #   namespace: seaweedfs
  #   chart: seaweedfs-csi-driver/seaweedfs-csi-driver
  #   version: 0.2.2
  #   values:
  #     - ./values/seaweedfs-csi-driver.values.yaml

  # pihole
  # - name: pihole
  #   namespace: pihole-system
  #   chart: mojo2600/pihole
  #   version: 2.26.1
  #   values:
  #     - ./values/pihole.values.yaml

  # Automatic DNS for pihole
  # - name: externaldns-pihole
  #   namespace: pihole-system
  #   chart: bitnami/external-dns
  #   version: 8.3.3
  #   values:
  #     - ./values/externaldns.values.yaml

  # - name: prometheus
  #   namespace: monitoring
  #   chart: prometheus-community/prometheus
  #   version: 25.26.0
  #   values:
  #     - ./values/prometheus.values.yaml

  # - name: grafana
  #   namespace: monitoring
  #   chart: grafana/grafana
  #   version: 8.4.5
  #   values:
  #     - ./values/grafana.values.yaml

  # - name: ollama
  #   namespace: ollama
  #   chart: ollama/ollama
  #   version: 0.54.0
  #   values:
  #     - ./values/ollama.values.yaml
  
  # - name: open-webui
  #   namespace: open-webui
  #   chart: open-webui/open-webui
  #   version: 3.1.7
  #   values:
  #     - ./values/open-webui.values.yaml

  # - name: home-assistant
  #   namespace: home-assistant
  #   chart: pajikos/home-assistant
  #   version: 0.2.74
  #   values:
  #     - ./values/home-assistant.values.yaml