# Homebrew install commands:
# brew install helm
# helm plugin install https://github.com/databus23/helm-diff
# brew install helmfile

# Apply commands:
# helmfile apply

# Modular helmfile structure
bases:
  - helmfiles/repositories.yaml
  - helmfiles/defaults.yaml

# Ordered deployment of services
helmfiles:
  - path: ./helmfiles/infrastructure.yaml 
  - path: ./helmfiles/network.yaml
  - path: ./helmfiles/security.yaml
  - path: ./helmfiles/gitops.yaml
  - path: ./helmfiles/applications.yaml
  
  # Uncomment to deploy experimental/optional services:
  # - path: ./helmfiles/not_used.yaml