apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-vault
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /nfs-share/vault
    server: 10.11.12.213